apiVersion: v1
kind: Namespace
metadata:
  name: test-calibrate-10k-500k  
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-calibrate-1
  namespace: test-calibrate-10k-500k
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-calibrate-1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: workload-calibrate-1
    spec:
      containers:
      - command:
        - sh
        - -c
        - |
          cd /data
          # create initial data 
          if [ ! -f initial ]
          then            
            for j in $(seq 1 25)
            do 
              for i in $(seq 1 400); do dd if=/dev/urandom of=$i.v$j.bin bs=500K count=1; echo "created $i.v$j.bin"; done
            done
            # all the initial filesystem is created we mark it
            # by creating an initial file if the pod restart it won't try to 
            touch initial
          fi 
          # implement churn rate notice the & 
          # at the end of the second for-loop 
          # this is to let the files renew happen during the sleep of 10 hours
          while true 
          do 
            for j in $(seq 1 5)
            do 
              for i in $(seq 1 400); do dd if=/dev/urandom of=$i.v$j.bin bs=500K count=1; echo "created $i.v$j.bin"; done &
            done
            sleep 36000
          done          
        image: docker.io/alpine:latest
        imagePullPolicy: IfNotPresent
        name: workload-calibrate-1-container
        securityContext: 
          allowPrivilegeEscalation: false
          capabilities: 
            drop: 
            - "ALL"
          runAsNonRoot: true 
          seccompProfile: 
            type: "RuntimeDefault"        
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - mountPath: /data
          name: data      
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: calibrate-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibrate-1
  namespace: test-calibrate-10k-500k
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  # storageClassName: ebs-sc